services:
  nemi-be:
    image: ${IMAGE_URI}
    pull_policy: always
    container_name: ${IMAGE_NAME}
    restart: unless-stopped
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 800M
          cpus: '0.8'
        reservations:
          memory: 400M
#    environment:
#      - SPRING_PROFILES_ACTIVE=dev
    # volumes:  # Uncomment if needed
    #   - ./logs:/app/logs
    #   - ./config:/app/config