spring:
  application:
    name: nemi-report
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://nemi-uat.cbwe2q8wsga5.ap-southeast-1.rds.amazonaws.com:5432/dev_nemi
    username: dev_nemi_report
    password: Nemi123#
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    #    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
          order_inserts: true
          order_updates: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: classpath:report-column-config.yml

server:
  port: 5204
  error:
    include-stacktrace: never
secret:
  jwt-public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArh1qU7sGe0uiquAuZo9+T4RTLZoG5NdtHtPCxcFp04EaTJFF+EmN/hwC0v3BXjNbvHYOPfUkmZ98QGeGXE6Q8xp3RGJafrmg6IAOzcWVSaVS4X0hlZjUNs5gW197ojhCCPRuWUSdSmAJG1i+CLQPn+pCBK7Wy2sJ6JTVtnuvs6LaUeqL9B7yE4LaMgEJo9ubi/TCrkD6dI4mxrqsVQVDpaHxau+sZbBsbGD/V4rWfFv7XqAbqWbam3gF/Qr2q/321sLkYjoSEG5sLxaDLgrDPk2moZ1PyLtuDpeF1DWygcK7XRsZjD3j4LkV2K4Ubi+P2wQCI+oZfM1XVlslzKKnVQIDAQAB"
  service-username: "nemi"
  service-password: "Nemi@2025@"
logging:
  level:
    root: info
    org.apache: off
    com:
      nemi: debug
  file:
    name: /tmp/log/nemi.log
  logback:
    rollingpolicy:
      file-name-pattern: /tmp/log/nemi.%d{yyyy-MM-dd}.%i.log
      max-history: 30
      max-file-size: 10MB
      total-size-cap: 1GB
      clean-history-on-start: false

management:
  server:
    port: 8082

report:
  base-url: https://nemi-dev-02.ecombase.net/nemi-report
  scale:
    vnd: 0
    other: 2
    percent: 2
    rate: 10
  date-pattern: "dd/MM/yyyy"
  business-today:
    hour-frame:
      - [0, 2]
      - [2, 4]
      - [4, 6]
      - [6, 8]
      - [8, 10]
      - [10, 12]
      - [12, 14]
      - [14, 16]
      - [16, 18]
      - [18, 20]
      - [20, 22]
      - [22, 24]
  compare-chart:
    step-days: 1

currency:
  base-url: https://nemi-dev-02.ecombase.net/nemi-system-manager
  version: v1
  currency-rate-url: currency-rate
  type:
    - USD
    - VND
